### PR TITLE
Filter entries by log level

### PR DESCRIPTION
**Pull request by stgleb**
Add ability to skip entries whose level is too low

### CODE REVIEW

**Comment by ripcurld0** [comment]
Hey @stgleb 

Can you tell me what you're exactly trying to resolve with this patch?
What did you try to do before opening this PR?

So I can grasp the use case and get a good decision whether it's good or not.

Thanks a lot for your time and for this patch, though. 👍

**Comment by stgleb** [comment]
Hello @ripcurld0 

My point was to adjust your plugin send logs according to specified log level.  I am working on high loaded system and if it will emit all logs including debug info to ELK than elastic search will definitely go down. That is why I want to adjust it. The same issue was with graylog logrus https://github.com/gemnasium/logrus-graylog-hook/issues/25 but they have levels field exported.

**Comment by ripcurld0** [comment]
@stgleb can you please squash these commits into one. It will be easier to review this that way.
Thanks 😃

**Comment by stgleb** [comment]
@ripcurld0 I think yes, I will remove it soon.

**Comment by ripcurld0** [comment]
I would prefer not to change `Hook` by adding more functions to it.
Maybe doing something like:

```
type LevelsHook struct {
   h Hook
   FireLevels []logrus.Levels
}

func (lh LevelsHook) Fire(e logrus.Entry) error {
  if lh.FireLevels[len(lh.FireLevels)-1] < e.Level {
    return nil
  }
  lh.h.Fire(e)
}

func NewLevelHook(h Hook, levels []logrus.Level) LevelHook {
  return LevelHook{h: h, FireLevel: levels}
}
```

If you want to make sure there is no race condition on `FireLevel` then wrap it in a function that uses locks or something.

**Pull request closed without merging**
