### PR TITLE
travis: update go versions to test against

### PR DESCRIPTION
**Pull request by thaJeztah**
noticed this in https://github.com/docker/distribution/pull/2941 😅

### CODE REVIEW

**Comment by thaJeztah** [comment]
@boaz0 ptal 🤗 👋

**Comment by thaJeztah** [comment]
I also noticed that

- a v1.0 is being worked on (not sure if that's still ongoing?)
- current tags are not SemVer (missing the last `.x`), which likely is the cause for go mod to not pick up tags

**Comment by thaJeztah** [comment]
Ahm needs a small update for newer go versions;

```
$ go tool vet .
vet: invoking "go tool vet" directly is unsupported; use "go vet"
The command "go tool vet ." exited with 1.
```

**Comment by boaz0** [comment]
Thanks a lot @thaJeztah. Sorry for the late response. :pray: :bowing_man:

**Comment by thaJeztah** [comment]
Thanks!

**Comment by thaJeztah** [comment]
Are you still working on doing a `v1.0.0` release or too soon? (wondering if a new tag would be possible otherwise, but I noticed that master already mentions v1.0.0); https://github.com/bshuster-repo/logrus-logstash-hook/compare/v0.4.1...master

**Comment by thaJeztah** [comment]
Thanks! Not a huge deal, but I noticed some PRs moving to `go mod` (and having tagged releases would probably help for those)

**Comment by boaz0** [comment]
Yes, I really need to work on it. I will deal with this soon. :smile:

**Pull request merged**
