### PR TITLE
Changing to the MIT License

### PR DESCRIPTION
**Pull request by lpetre**
As discussed in https://github.com/bshuster-repo/logrus-logstash-hook/pull/2, moving to the same license as logrus.

You may want to get other contributors to sign off on this switch (attn @ly-william)

### CODE REVIEW

**Comment by ripcurld00d** [comment]
@ly-william your agreement to this change is necessary. Please reply to that ASAP, thanks.

@lpetre, in case it will take more than 1 week, I guess I have to revert his change.

Thanks.

**Comment by ly-william** [comment]
LGTM, go ahead

**Comment by ripcurld00d** [comment]
@ly-william thanks a lot for your fast response!

**Comment by ly-william** [comment]
@ripcurld00d Sure np, thanks for notifying me :)

**Pull request merged**
