### PR TITLE
Reconnect functionality

### PR DESCRIPTION
**Pull request by dahankzter**
I see lots of dropped connections when I use this so I thought using https://github.com/teh-cmc/goautosocket for automatic reconnects would be neat.

### CODE REVIEW

**Comment by dahankzter** [comment]
What do you think @lkysow @lpetre can this be applied?

**Comment by ripcurld00d** [comment]
Hi @dahankzter,
:confetti_ball: :tada: :balloon:
Thanks for your time and for the changes.
Please, read my review and let me know if you need my help.

In general, you raised a good point. Nevertheless, to make this hook small, I try not to add packages :package: (unless they come with the Go language) to this repository.

Thanks.

**Comment by dahankzter** [comment]
Perhaps we can do both? The api hasn't changed by this so users should not
be affected. Then we can try out some way to make it more configurable
later?

The idea is to quickly get reconnect functionality in and later supply a
way to inject or configure the details.

What do you think?

**Comment by ripcurld00d** [comment]
Hi @dahankzter,

I'm deadly sorry :cry:  but your claim is not persuasive enough for me to merge this, because packages that have multiple dependencies are a nightmare to maintain.

The only way around it is providing a flexible API that gives the user the capability to decide how to initialize the hook.

I really would love seeing you working on it. It will be amazing!

@lkysow @lpetre @ly-william - feel free to give feedback.

Thanks.

**Comment by dahankzter** [comment]
No problem. How about making it possible to inject a tiny interface that
lives in this package that the user can implement? For example the
autoreconnect library here or any other connection handling library could
then be used.

What do you think?

**Comment by ripcurld00d** [comment]
If I understood you correctly, then :+1: !

For example, to use goautosocket:

```go
sock, err := gau.Dial("tcp", "logstash.corp.io:9999")
if err != nil {
    log.Fatal(err)
}
hook := logrus_logstash.NewHookFromConn(sock, "myApp", logrus.Fields{})
...
```

What is your opinion?

**Comment by dahankzter** [comment]
Very much like this yes.

**Comment by ripcurld00d** [comment]
Then you got a :green_heart: light! :laughing:

**Comment by dahankzter** [comment]
How does this look?
Both previously existing constructor methods now have counterparts that take a connection as well.

**Comment by ripcurld00d** [comment]
Awesomeness!!! :trophy: :fire:

**Comment by dahankzter** [comment]
😀

**Comment by ripcurld00d** [comment]
When the tests are :green_apple:, these changes will be merged. :+1:

**Comment by ripcurld00d** [comment]
merged in 1...2...3...:bomb:

**Comment by dahankzter** [comment]
Nice, thx for good collaboration peeps!

**Pull request merged**
